services:
  - type: web
    name: casperdev-portfolio
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn casperdev.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: casperdev.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: casperdev.onrender.com
