# Generated by Django 5.0.7 on 2025-09-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_project_github_link_remove_project_live_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='site_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
